---
name: Tests
# yamllint disable rule:truthy
on: [push]
# yamllint enable

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci
      - run: npm run build -s
      - run: npm run lint -s
      - run: npm run test -s
